public with sharing class YP_ProductApartmentWrapper {

    public String name;
    public Double area;
    public Integer floors;
    public Integer bedrooms;
    public Integer bathrooms;
    public Boolean attic;
    public Boolean basement;
    public String contentId;
    public String contentVersionId;

    public YP_ProductApartmentWrapper(String name, Double areaInteger floorsInteger bedroomsInteger bathroomsBoolean atticBoolean basementString contentIdString contentVersionId) {

    }
}