name: Deploy with validation on feature push


on:
  push:
    branches:
      - 'feature/**'

jobs:
  push-feature:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Install SFDX CLI'
      run: |
        wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
        mkdir sfdx-cli
        tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
        ./sfdx-cli/install
    - name: 'Get sfdx auth url'
      shell: bash
      run: |
        echo ${{ secrets.SFDX_AUTH_URL}} > ./AUTHORIZED_URL.txt
    - name: 'Authenticate org'
      run: sfdx auth:sfdxurl:store -f ./AUTHORIZED_URL.txt -s -a DevOrg
    - name: 'Deploy with validation'
      run: |
        sfdx force:source:deploy -p "force-app" --checkonly
