name: Deploy with validation on feature push


on:
    push:
        branches:
        - 'force-app/**'     
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
        - name: Install Salesforce CLI
              run: |
                  wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
                  mkdir sfdx-cli
                  tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
                  ./sfdx-cli/install
        - name: 'Populate auth file with SFDX_URL secret'
              shell: bash
              run: 'echo ${{ secrets.YOURPLACESPROD }} > SFDX_Q'

        - name: 'Authenticate to Production Org'
              run: sfdx auth:sfdxurl:store -f SFDX_Q
  
        - name: 'Run checkonly deploy'
              run: sfdx force:source:deploy -x manifest/package.xml --testlevel RunLocalTests --json --checkonly
